version: '3'

services:
  web:
    image: prom/prometheus 
    container_name: prom0
    network_mode: bridge
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  prometheus:
